---

# Specific install tasks for Debian family

- name: 'INSTALL | APT | Install repository'
  template:
    src: "{{ role_path }}/templates/repositories/nginx_ubuntu.list.j2"
    dest: "/etc/apt/sources.list.d/{{ nginx_repository_file.name }}"
    owner: "{{ nginx_repository_file.owner }}"
    group: "{{ nginx_repository_file.group }}"
    mode: "{{ nginx_repository_file.mode }}"
  register: 'nginx_register_repository_list'


- name: 'INSTALL | APT | Manage repository key'
  apt_key:
    url: "{{ nginx_repository_key_url }}"
  register: 'nginx_register_repository_key'


- name: 'INSTALL | APT | Update apt cache if repository changed'
  apt:
    update_cache: True
  when: "nginx_register_repository_list.changed \
        or nginx_register_repository_key.changed"


- name: 'INSTALL | APT | Update apt cache if repository not changed'
  apt:
    update_cache: True
    cache_valid_time: "{{ nginx_repository_cache_valid_time }}"
