---

- name: Install certificate file
  become: True
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: restart nginx
  with_items: "{{ nginx_ssl_certificate_files }}"
  when: "{{ item.content != '' }}"

- name: Install key file
  become: True
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: restart nginx
  with_items: "{{ nginx_ssl_key_files }}"
  when: "{{ item.content != '' }}"

- name: Create self signed certificate and private key
  become: True
  command: "openssl req -new \
              -subj '/CN={{ nginx_ssl_self_signed_cn }}' \
              -newkey rsa:2048 -sha512 -days 3650 -nodes -x509 \
              -keyout /etc/ssl/private/{{ ansible_fqdn }} \
              -out /etc/ssl/certs/{{ ansible_fqdn }}"
  args:
    creates: "/etc/ssl/certs/{{ ansible_fqdn }}"
  notify: restart nginx

