---

- name: 'CONFIGURE | Delete default configuration files'
  file:
    path: "{{ item }}"
    state: 'absent'
  notify: 'HANDLER | Restart Nginx'
  with_items: "{{ nginx_config_paths.files.default }}"
  when: "nginx_delete_default_config_files"


- name: 'CONFIGURE | Create server configuration folders'
  file:
    path: "{{ item }}"
    owner: "{{ nginx_config_permissions.folders.owner }}"
    group: "{{ nginx_config_permissions.folders.group }}"
    mode: "{{ nginx_config_permissions.folders.mode }}"
    state: 'directory'
  with_items:
    - "{{ nginx_config_paths.folders.sites_available }}"
    - "{{ nginx_config_paths.folders.sites_enabled }}"


- name: 'CONFIGURE | Manage main configuration file'
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: "{{ nginx_config_paths.files.main }}"
    owner: "{{ nginx_config_permissions.files.owner }}"
    group: "{{ nginx_config_permissions.files.group }}"
    mode: "{{ nginx_config_permissions.files.mode }}"
  notify: 'HANDLER | Restart Nginx'


- name: 'CONFIGURE | Manage items configuration'
  include_tasks: "{{ role_path }}/tasks/configure_items.yml"
  notify: 'HANDLER | Restart Nginx'


- name: 'CONFIGURE | manage logorotate'
  template:
    src: "{{ role_path }}/templates/logrotate.j2"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default (0644) }}"
  with_items: "{{ nginx_logrotate_config }}"
  when: default_nginx_logrotate_config_modify
