---

- name: 'Delete default configuration files'
  file:
    path: "{{ item }}"
    state: 'absent'
  notify: 'HANDLER | Restart Nginx'
  with_items: "{{ nginx_config_paths.files.default }}"
  when: "nginx_delete_default_config_files"


- name: 'Create server configuration folders'
  file:
    path: "{{ item }}"
    owner: "{{ nginx_config_permissions.folders.owner }}"
    group: "{{ nginx_config_permissions.folders.group }}"
    mode: "{{ nginx_config_permissions.folders.mode }}"
    state: 'directory'
  with_items:
    - "{{ nginx_config_paths.folders.sites_available }}"
    - "{{ nginx_config_paths.folders.sites_enabled }}"


- name: 'Manage main configuration file'
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: "{{ nginx_config_paths.files.main }}"
    owner: "{{ nginx_config_permissions.files.owner }}"
    group: "{{ nginx_config_permissions.files.group }}"
    mode: "{{ nginx_config_permissions.files.mode }}"
  notify: 'HANDLER | Restart Nginx'


- name: 'Manage servers configuration'
  template:
    src: "{{ role_path }}/templates/server.conf.j2"
    dest: "{{ nginx_config_paths.folders.sites_available }}/{{ item.name }}.conf"
    owner: "{{ nginx_config_permissions.files.owner }}"
    group: "{{ nginx_config_permissions.files.group }}"
    mode: "{{ nginx_config_permissions.files.mode }}"
  notify: 'HANDLER | Restart Nginx'
  with_items: "{{ nginx_servers }}"


- name: 'Manage servers activation'
  file:
    src: "{{ nginx_config_paths.folders.sites_available }}/{{ item.name }}.conf"
    dest: "{{ nginx_config_paths.folders.sites_enabled }}/{{ item.name }}.conf"
    state: "{{ item.is_enabled | ternary('link', 'absent') }}"
  notify: 'HANDLER | Restart Nginx'
  with_items: "{{ nginx_servers }}"


- name: 'Check if configuration is valid'
  command: 'nginx -t'
  changed_when: False
