---

# Main tasks file for nginx role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::nginx'
    - 'role::nginx::config'
    - 'role::nginx::init'
    - 'role::nginx::install'


- name: 'INSTALL | Manage OS family specific installation tasks'
  become: True
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::nginx'
    - 'role::nginx::install'


- name: 'CONFIG | Manage configuration'
  become: True
  include: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'role::nginx'
    - 'role::nginx::config'


- name: 'INSTALL | Enable services'
  become: True
  service:
    name: "{{ nginx_service_name }}"
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
  tags:
    - 'role::nginx'
    - 'role::nginx::config'
    - 'role::nginx::install'
