"""
Role tests
"""

from testinfra.utils.ansible_runner import AnsibleRunner

testinfra_hosts = AnsibleRunner('.molecule/ansible_inventory').get_hosts('all')


def test_site_configuration(host):
    """
    Test site configuration file structure
    """

    config_file = '/etc/nginx/sites-available/foobar.conf'

    expected_content = [
        u'# Ansible managed: Do NOT edit this file manually!',
        u'server {',
        u'    listen 80;',
        u'    root /var/www/foo;',
        u'    server_name localhost;',
        u'    index index.html;',
        u'    location /foo {',
        u'        try_files $uri =404;',
        u'        root /var/www/foo;',
        u'    }',
        u'    location /bar {',
        u'        try_files $uri =404;',
        u'        root /var/www/bar;',
        u'    }',
        u'}'
    ]

    current_content = filter(
        None,
        host.file(config_file).content_string.split('\n'))

    assert current_content == expected_content
