---

# Handlers main file for nginx role

- name: 'HANDLER | Restart Nginx'
  become: True
  service:
    name: "{{ nginx_service_name }}"
    state: 'restarted'


- name: 'HANDLER | Reload Nginx'
  become: True
  service:
    name: "{{ nginx_service_name }}"
    state: 'reloaded'
